### ISSUE TITLE
Hangs when enumerating stream

### ISSUE THREAD

**Issue by JeremyButts** [splunk/splunk-sdk-csharp#45]
Version: 2.2.3
Platform: ASP.net MVC 5

After performing a one shot search that returns no results and then enumerating over the SearchResultStream the application hangs.  No exception is thrown.

**Comment by shakeelmohamed** [comment]
Hi @JeremyButts, can you create an issue on the [C# SDK 2.x repo](https://github.com/splunk/splunk-sdk-csharp-pcl)? This repo is for the 1.x SDK

**Comment by JeremyButts** [comment]
Sure
